name: az_url_lister
description: Lists all your shortened URLs
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  tray_manager: ^0.2.0
  cupertino_icons: ^1.0.2
  ionicons: ^0.2.1
  bot_toast: ^4.0.1
  window_manager: ^0.2.7
  screen_retriever: ^0.1.4
  azstore: ^1.0.3
  grouped_list: ^5.1.2
  intl: ^0.17.0
  url_launcher: ^6.1.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/