name: tray_manager_example
description: Demonstrates how to use the tray_manager plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  tray_manager: ^0.2.0
  cupertino_icons: ^1.0.2
  bot_toast: ^4.0.1
  preference_list: ^0.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/